### PR TITLE
add prop-shop and example propType with description

### PR DESCRIPTION
**Pull request by PaulieScanlon**
Hey @spences10  Here's an alpha of "Project Prop".

As you can see, it's now called PropShop 😊

If you spin up `dev` then navigate to `http://localhost:9988/prop-shop` you should see all the PropType information for `.js` files in your blog.

... there wasn't actually any propTypes added so i've popped one or two in otherwise the plugin errors.

### CODE REVIEW

**Review by spences10 — APPROVED** [review]

**Comment by spences10** [comment]
Hey @PaulieScanlon 👋 

So, I'll move this off to it's own branch for now, can I check this out in the deployed url from nowsh?

Also, wow, thanks, much appreciated.

**Comment by spences10** [comment]
I'm getting build errors @PaulieScanlon did you try building your end before submitting the PR?

Excerpt from nowsh:

image

**Comment by PaulieScanlon** [comment]
@spences10 i do get a build error but it's related to `process.env.GATSBY_FATHOM_TRACKING_ID_THE_LOCALHOST_BLOG` i guess you have env vars right. 

Nothing in the plugin touches `gatsby-node.js` so i don't think that's related ... is it?

**Comment by spences10** [comment]
Ok, yeah, you'll need to create a `.env.production` file and add a bullshit env var for the analytics


```text
GATSBY_FATHOM_TRACKING_ID_THE_LOCALHOST_BLOG=bullshit
```

Maybe I should add example `.env` files?? 🤔

**Comment by PaulieScanlon** [comment]
@spences10 i've added .env.production and popped in `GATSBY_FATHOM_TRACKING_ID_THE_LOCALHOST_BLOG='123'`

...but i now get this error:
 `WebpackError: siteId must be provided when using the hosted version of Fathom`

**Comment by spences10** [comment]
`bullshit` not a good enough env.var for you Paul 😂 

So, there's no reason this shouldn't build, could you try with no quotes and try with 8 charecters?

```bash
GATSBY_FATHOM_TRACKING_ID_THE_LOCALHOST_BLOG=12345678
```

Or, failing that use `bullshit` 🙃

**Comment by PaulieScanlon** [comment]
@spences10 ok with `12345678` it builds fine locally, no errors. Is this build error relating to something else i wonder.

**Comment by spences10** [comment]
I get the same error when running on the dev server:

image

**Comment by PaulieScanlon** [comment]
What happens if you comment out the plugin In config? It runs in dev and build fine for me 🤷‍♂️

**Comment by spences10** [comment]
I'm thinking about moving the blog over to TypeScript, shouldn't be too hard right @PaulieScanlon?

**Comment by PaulieScanlon** [comment]
You shouldn’t have too many problems if you use https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/ its only when creating plugins that ts becomes a bit of a problem because of how tsconfig/babel and Gatsby need to be setup in a specific way. This plugin does all take for you and will work out of the box in a straight up Gatsby blog. Naturally you’ll need to spend a bit of time creating interfaces and types for all your props and function args but it should be ok.

**Pull request merged**
